[package]
name = "nu_plugin_test"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "nu_plugin_test"
bench = false

[dependencies]
nu-plugin = "0.109.1"
nu-protocol = { version = "0.109.1", features = ["plugin"] }
